name: Generate Documentation

on:
  push:
    branches:
      - main # Or your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: leanprover-community/docgen-action/.github/workflows/docgen.yml@v4
